project: 
  type: website
  output-dir: docs
  
website:
  page-navigation: true  
  title: "gisma knowledge base"
  site-url: https://gisma-courses.github.io/gisma-knowledge-base
  
  repo-url: https://github.com/gisma-courses/gisma-knowledge-base
  repo-actions: [edit, issue]
  
  page-footer: "gisma (2021)" 
 
  sidebar:
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/gisma-courses/gisma-knowledge-base
        text: "gisma repo"  
      - icon: sun
        text: "dark theme"
      - icon: moon
        text: "light theme"


    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Welcome"
        contents:
          - index.qmd
          - about.qmd


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto