project: 
  type: website
  output-dir: docs
  
website:
  page-navigation: true  
  title: "gisma knowledge base"
  site-url: https://gisma-courses.github.io/gisma-knowledge-base

  sidebar:
    logo: https://github.com/gisma-courses/gisma-knowledge-base/blob/master/images/climatroof-sp.jpg
    pinned: true
    align: center
    tools: 
      - icon: sun
        text: "dark theme"
      - icon: moon
        text: "light theme"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: "Welcome"
        contents:
          - index.qmd
          - about.qmd


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    
execute:
  freeze: auto

filters:
  - include-files.lua
  - quarto
