project: 
  type: website
  output-dir: docs
  
website:
  page-navigation: true  
  title: "gisma knowledge base"
  site-url: https://gisma-courses.github.io/gisma-knowledge-base

 sidebar:
    logo: https://github.com/gisma-courses/gisma-knowledge-base/blob/master/images/climatroof-sp.jpg
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nasa-openscapes.github.io
        text: "NASA-Openscapes website"
      - icon: github
        href: https://github.com/nasa-openscapes/2021-Cloud-Hackathon
        text: "2021 Cloud Hackathon repo"
    

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    
execute:
  freeze: auto

