project: 
  type: website
  output-dir: docs
  
website:
  open-graph: true
  page-navigation: true  
  
  search: 
    location: navbar
    type: textbox
  title: "gisma knowledge base"
  site-url: https://gisma-courses.github.io/gisma-knowledge-base
  
  repo-url: https://github.com/gisma-courses/gisma-knowledge-base
  repo-actions: [edit, issue]
    
  page-footer: "gisma (2021)" 
  twitter-card:
    creator: "@creuden"
  comments:
    utterances:
      repo: gisma-courses/gisma-knowledge-base
  navbar:
    right:
      - icon: house
        text: Home
        href: index.html
      - icon: question
        text: FAQ
        href: /base/faq.qmd
      - icon: calendar
        text: Ilias
        href: https://ilias.uni-marburg.de/login.php?target=&client_id=UNIMR&cmd=force_login
    tools: 
      - icon: github
        href: https://github.com/gisma-courses/gisma-knowledge-base
        text: "gisma repo" 


  sidebar:
    logo: /images/logo.jpg
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Welcome"
        contents:
          - index.md
          - base/about.md
      - text: "---"
      - section: "Low Cost UAV"
        contents:
          - href: https://gisma-courses.github.io/LV-uav-workflow/modules/module-introduction/
            text: Basic Readings        
          - href: https://gisma-courses.github.io/LV-uav-workflow/modules/module-fieldwork/
            test: uav/Flight Planning
          - uav/products.qmd
      - text: "---"
      - section: "Micro-Climate"
        contents:
          - mclim/mc-index.qmd
          - mclim/sensors.qmd


format:
  html:
    theme:
      light: lumen
      dark: [lumen, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto