project: 
  type: website
  output-dir: docs
  
website:
  open-graph: true
  page-navigation: false  
  title: "gisma knowledge base"
  site-url: https://gisma-courses.github.io/gisma-knowledge-base
  
  repo-url: https://github.com/gisma-courses/gisma-knowledge-base
  repo-actions: [edit, issue]
    
  page-footer: "gisma (2021)" 
  twitter-card:
    creator: "@creuden"
  #comments:
  #  utterances:
  #    repo: gisma-courses/mm218.dev
  navbar:
    right:
      - icon: house
        text: Home
        href: index.html
      - icon: question
        text: FAQ
        href: faq.qmd
      - icon: calendar
        text: Ilias
        href: https://ilias.uni-marburg.de/login.php?target=&client_id=UNIMR&cmd=force_login
    tools: 
      - icon: github
        href: https://github.com/gisma-courses/gisma-knowledge-base
        text: "gisma repo" 


  sidebar:
    logo: https://gisma-courses.github.io/gc/assets/images/gisma-13.jpg
    pinned: true
    align: center



    style: "docked"
    search: true
    collapse-level: 1
    
    contents:
      - section: "Welcome"

        contents:

          - index.md
          - about.md
      - section: "Low Cost UAV Workflows"
        contents:
          - href: https://gisma-courses.github.io/LV-uav-workflow/modules/module-introduction/
            text: Basic Readings        
          - href: https://gisma-courses.github.io/LV-uav-workflow/modules/module-fieldwork/
            test: Flight Planning
          - products.qmd
      - section: "Micro-Climate"
        contents:
          - mc-index.qmd
          - sensors.qmd


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true


filters:
  - include-files.lua
  - quarto